force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/BuyAmount__c.field-meta.xml
<CustomField>
    <fullName>BuyAmount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/BuyCurrency__c.field-meta.xml
<CustomField>
    <fullName>BuyCurrency__c</fullName>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/SellAmount__c.field-meta.xml
<CustomField>
    <fullName>SellAmount__c</fullName>
    <label>Sell Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/SellCurrency__c.field-meta.xml
<CustomField>
    <fullName>SellCurrency__c</fullName>
    <description>Picklist used to store trade&apos;s currency</description>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currencies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <masterLabel>Currencies</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TradeSelector.cls
public class TradeSelector {
    private String query;
    private Set<String> fields;
    private String conditions;
    private String orderBy;
    private Integer limitOf;

    private static Set<String> DEFAULT_FIELDS = new Set<String>{
        'Id',
        'BuyAmount__c',
        'BuyCurrency__c',
        'CreatedDate',
        'Rate__c',
        'SellAmount__c',
        'SellCurrency__c',
        'Name'
    };

    public TradeSelector () {
        this(DEFAULT_FIELDS);
    }

    public TradeSelector (Set<String> fields) {
        this.fields = fields;
        this.query = 'SELECT ';
    }

    public TradeSelector getOrderByCreatedDateDesc() {
        orderBy = orderBy == null ? 'CreatedDate DESC' : orderBy + ', CreatedDate DESC';
        return this;
    }

    public TradeSelector getWithLimit(Integer limitOf) {
        this.limitOf = limitOf;
        return this;
    }

    public String buildQuery() {
        query += String.join(new List<String>( this.fields ), ',') + ' FROM Trade__c';
        if (this.conditions != null) {
            query += ' WHERE ' + this.conditions;
        }

        if (this.orderBy != null) {
            query += ' ORDER BY ' + this.orderBy;
        }

        if (this.limitOf != null) {
            query += ' LIMIT ' + this.limitOf;
        }
        return this.query;
    }

    public List<Trade__c> getData() {
        try {
            return (List<Trade__c>) Database.query( this.buildQuery() );
        }
        catch(Exception ex) {
            throw new SelectorException('Error retrieving trade: ' + ex.getMessage() + ex.getStackTraceString());
        }
    }

    public class SelectorException extends Exception {} 
}