force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/BuyCurrency__c.field-meta.xml
<CustomField>
    <fullName>BuyCurrency__c</fullName>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currencies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <masterLabel>Currencies</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TradesViewController.cls
public with sharing class TradesViewController {
    @testVisible
    private static TradesService tradeService;

    private static TradesService getTradeService() {
        if (tradeService == null) {
            tradeService = new TradesService();
        }
        return tradeService;
    }

    @AuraEnabled(cacheable=true)
    public static List<Trade__c> getTrades(Integer limitOf) {
        return getTradeService().getTrades(limitOf);
    }
    
    @AuraEnabled(cacheable=false)
    public static List<Rate> getRates(String baseCurrency) {
        //get currencies values
        TradesService.LatestRatesForCurrency latestRates = getTradeService().getLatestRates(
            baseCurrency, 
            SObjectUtils.getPicklistValuesList('Trade__c', 'BuyCurrency__c')
        );

        List<Rate> rates = new List<Rate>();
        for (TradesService.Rate rateCurr : latestRates.rates) {
            rates.add(new Rate(rateCurr.currencyName, rateCurr.rate));
        }
        return rates;
    }

    @AuraEnabled(cacheable=false)
    public static String publishTradeEvent(Id tradeId) {
        return getTradeService().submitNewTradeEvent(tradeId);
    }

    public class Rate {
        @AuraEnabled
        public String toCurrency;
        @AuraEnabled
        public Double value; 

        public Rate(String toCurrency, Double value) {
            this.toCurrency = toCurrency;
            this.value      = value;
        }
    }
}