force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/BuyAmount__c.field-meta.xml
<CustomField>
    <fullName>BuyAmount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/BuyCurrency__c.field-meta.xml
<CustomField>
    <fullName>BuyCurrency__c</fullName>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/SellAmount__c.field-meta.xml
<CustomField>
    <fullName>SellAmount__c</fullName>
    <label>Sell Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/SellCurrency__c.field-meta.xml
<CustomField>
    <fullName>SellCurrency__c</fullName>
    <description>Picklist used to store trade&apos;s currency</description>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currencies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <masterLabel>Currencies</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TradeEventService.cls
public with sharing class TradeEventService {
    private String LATEST_RATE_CREDENTIAL = '5IAvTHrI45AxOzRrUSLckZGrAO6Ne2F7';
    private String LATEST_RATE_PATH       = 'FixerAPI/latest?symbols={0}&base={1}';
    private Integer DEFAULT_LIMIT         = 10;
    private String MESSAGE_BODY_MODEL     = Label.NewTradeChatterMessage;

    private TradeSelector tradeSelector;

    public TradeEventService() {
        this.tradeSelector = new TradeSelector();
    }

    public void postNewTradeMessageToQueueMembers(List<Id> tradeIds, String queueName) {
        List<Trade__c> trades = this.tradeSelector.getTradesWithIds(tradeIds).getData();
        Set<Id> userIdsToPost = this.getQueueMembersIds(queueName);

        List<String> messages = new List<String>();
        for (Trade__c trade : trades) {
            messages.add(buildMessage(trade));
        }
        ChatterUtils.postMessagesTo(userIdsToPost, messages);
    }

    private Set<Id> getQueueMembersIds(String queueName) {
        Set<Id> userIds = new Set<Id>();
        Map<Id, Group> queues = new Map<Id, Group>([SELECT Id FROM Group WHERE Type='Queue' AND DeveloperName=:queueName]);
        for (GroupMember member : [SELECT UserOrGroupId FROM GroupMember WHERE GroupId IN :queues.keySet()]) {
            userIds.add(member.UserOrGroupId);
        }
        return userIds;
    }

    private String buildMessage(Trade__c trade) {
        List<Object> msgInfo = new List<Object>{
            trade.SellCurrency__c,
            trade.SellAmount__c.format(),
            trade.BuyCurrency__c,
            trade.BuyAmount__c.format(),
            trade.Rate__c.format(),
            Trade.CreatedDate.format(),
            URL.getSalesforceBaseUrl().toExternalForm() + '/' + trade.Id
        };
        return String.format(MESSAGE_BODY_MODEL, msgInfo);
    }
}