force-app/main/default/objects/NewTradeEvent__e/NewTradeEvent__e.object-meta.xml
<CustomObject>
    <label>New Trade Event</label>
    <pluralLabel>New Trades Event</pluralLabel>
</CustomObject>

force-app/main/default/objects/NewTradeEvent__e/fields/EventBody__c.field-meta.xml
<CustomField>
    <fullName>EventBody__c</fullName>
    <description>Payload for event with list of trade ids.</description>
    <label>Event Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NewTradeEventTest.cls
@isTest
private class NewTradeEventTest {
    @isTest
    private static void insertEvent_shouldinsertEvents() {
        Id tradeId = fflib_IDGenerator.generate(Trade__c.SObjectType);
        List<Id> tradeIds = new List<Id>{tradeId};
        NewTradeEvent__e newEvent = new NewTradeEvent__e(
            EventBody__c = JSON.serialize(tradeIds)
        );
        Test.startTest();
        Database.SaveResult eventResult = EventBus.publish(newEvent);
        Test.stopTest();
        System.assertEquals(true, eventResult.isSuccess());
    }
}