force-app/main/default/objects/NewTradeEvent__e/NewTradeEvent__e.object-meta.xml
<CustomObject>
    <label>New Trade Event</label>
    <pluralLabel>New Trades Event</pluralLabel>
</CustomObject>

force-app/main/default/objects/NewTradeEvent__e/fields/EventBody__c.field-meta.xml
<CustomField>
    <fullName>EventBody__c</fullName>
    <description>Payload for event with list of trade ids.</description>
    <label>Event Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/NewTradeEventHandler.cls
public with sharing class NewTradeEventHandler extends TriggerHandler {
    private String TRADE_REVIEWERS_QUEUE = 'TradeReviewers';
    private TradeEventService tradeEventService;

    public NewTradeEventHandler() {
        this.tradeEventService = new TradeEventService();
    }

    public override void afterInsert() {
        List<Id> tradeIds = new List<Id>();
        for (NewTradeEvent__e trade : (List<NewTradeEvent__e>) Trigger.new) {
            tradeIds.addAll((List<Id>)JSON.deserialize(trade.EventBody__c, List<Id>.class));
        }
        this.tradeEventService.postNewTradeMessageToQueueMembers(tradeIds, TRADE_REVIEWERS_QUEUE);
    }
}